services:
  - name: "FIBOS 123"
    api:
      - url: "https://www.fibos123.com"
      - url: "https://snapshots.fibos123.com"
  - name: "FIBOS API"
    api:
      - url: "https://to-rpc.fibos.io/v1/chain/get_info"
      - url: "https://rpc-mainnet.fibos123.com/v1/chain/get_info"

      
