timeout: 5
retry: 2
max_log_days: 30
services:
  - name: "GitHub API"
    health:
      - url: "https://api.github.com"
        method: "GET"
        status_code: 200
    api:
      - url: "https://api.github.com/repos/wcy-dt/ponghub"
        method: "GET"
        status_code: 200
        response_regex: "full_name"
  - name: "Ch3nyang's  Websites"
    health:
      - url: "https://docker-registry.ch3nyang.top/health"
        method: "GET"
        status_code: 200
      - url: "https://2024.ch3nyang.top/health"
        method: "GET"
        status_code: 200
      - url: "https://file.ch3nyang.top"
        method: "GET"
        status_code: 200